### ISSUE TITLE
UnityEditor high CPU usage after adding subAsset

### ISSUE THREAD

**Issue by TMPxyz** [mob-sakai/SubAssetEditor#2]
The 'hasSelectionChanged' flag should be set back to **false** around line291;
Otherwise the **AssetDatabase.Refresh()** is called repeatedly which would drag down the unity editor.

```
if (hasSelectionChanged)
{
	AssetDatabase.SaveAssets();
	AssetDatabase.Refresh();
	OnSelectionChanged(current);
        hasSelectionChanged = false; // <- here
}
```

**Comment by mob-sakai** [comment]
Hi @TMPxyz 

Wow, I will fix it!
Many thanks:)
