### ISSUE TITLE
Huge freezes with prefabs

### ISSUE THREAD

**Issue by Artein** [mob-sakai/SubAssetEditor#6]
**Describe the bug**
When selecting Prefab with hundreds of gameobjects SubAsset window freezes Unity.

**To Reproduce**
1. Create Prefab with hundreds of game objects
2. Open SubAsset window
3. Select created prefab
4. Huge freeze

**Expected behavior**
Must work without freezes

**Environment (please complete the following information):**
 - Version 1.0.0
 - Platform: Editor(Windows/Mac)
 - Unity version: 2021.3.5f1

**Additional context**
Seems like the problem is that SubAsset editor tries to show all gameobjects (Transform and RectTransform components) of a prefab in SubAsset tab. This creates a huge freezes with prefabs containing hundreds of gameobjects

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
It appears that in some version of Unity, Transforms, etc. are now displayed as SubAssets.

**Comment by mob-sakai** [comment]
fixed in 1.0.1

**Comment by Artein** [comment]
Well, now Editor is at least usable. But still there is a freeze for a few seconds.

My prefab is about 100 rows. Each row has 7 cells. Each cell has Terrain + PropHolder.
In total about 100 rows, 700 cells, 700 Terrains, 700 PropHolders.

Only Terrain has components - Physics Body and Physics Shape (both DOTS authoring components).
Seems like those empty entries from those components.

Is it possible to fix empty entries?
<img width="407" alt="Screenshot 2022-07-07 at 22 26 35" src="https://user-images.githubusercontent.com/1109722/177857011-c1e6dce0-20fa-4340-aeb4-67df55894379.png">
<img width="768" alt="Screenshot 2022-07-07 at 22 27 46" src="https://user-images.githubusercontent.com/1109722/177857021-c597864d-b34c-4247-91c8-7eaf4e8cc566.png">
[Platform_Crystals_Dunes_Block_Basic.prefab.zip](https://github.com/mob-sakai/SubAssetEditor/files/9066832/Platform_Crystals_Dunes_Block_Basic.prefab.zip)

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
fixed in v1.1.0
